name: nbapp
description: "To follow NBA games and stats"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  domain:
    path: ./domain
  logger: ^2.3.0
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_fonts: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
