name: nbapp
description: "To follow NBA games and stats"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  domain:
    path: ./domain

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
